// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// loss_grad_rcpp
Rcpp::List loss_grad_rcpp(const arma::vec& u, const arma::vec& w, const arma::mat& Ax, const arma::mat& X, const arma::vec& Y, const double sigma, const double kappa, const double alpha, const arma::vec& adaptive_weights, const double eps);
RcppExport SEXP _krtexas_loss_grad_rcpp(SEXP uSEXP, SEXP wSEXP, SEXP AxSEXP, SEXP XSEXP, SEXP YSEXP, SEXP sigmaSEXP, SEXP kappaSEXP, SEXP alphaSEXP, SEXP adaptive_weightsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ax(AxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type adaptive_weights(adaptive_weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_grad_rcpp(u, w, Ax, X, Y, sigma, kappa, alpha, adaptive_weights, eps));
    return rcpp_result_gen;
END_RCPP
}
// grad_fun_fast_cpp
arma::vec grad_fun_fast_cpp(const arma::vec& u, const arma::vec& w, const arma::mat& Ax, const arma::mat& X, const arma::vec& Y, const double sigma, const double kappa, const arma::vec& adaptive_weights);
RcppExport SEXP _krtexas_grad_fun_fast_cpp(SEXP uSEXP, SEXP wSEXP, SEXP AxSEXP, SEXP XSEXP, SEXP YSEXP, SEXP sigmaSEXP, SEXP kappaSEXP, SEXP adaptive_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ax(AxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type adaptive_weights(adaptive_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_fun_fast_cpp(u, w, Ax, X, Y, sigma, kappa, adaptive_weights));
    return rcpp_result_gen;
END_RCPP
}
// interior_scores_exp_kernel_cpp
arma::vec interior_scores_exp_kernel_cpp(const arma::mat& X, const arma::vec& gamma, bool exclude_self, bool normalize);
RcppExport SEXP _krtexas_interior_scores_exp_kernel_cpp(SEXP XSEXP, SEXP gammaSEXP, SEXP exclude_selfSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(interior_scores_exp_kernel_cpp(X, gamma, exclude_self, normalize));
    return rcpp_result_gen;
END_RCPP
}
// find_interior_points
Rcpp::List find_interior_points(const arma::mat& X, const arma::vec& gamma, int m, bool exclude_self, bool normalize);
RcppExport SEXP _krtexas_find_interior_points(SEXP XSEXP, SEXP gammaSEXP, SEXP mSEXP, SEXP exclude_selfSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(find_interior_points(X, gamma, m, exclude_self, normalize));
    return rcpp_result_gen;
END_RCPP
}
// loss_fun_fast_cpp
double loss_fun_fast_cpp(const arma::vec& u, const arma::vec& w, const arma::mat& Ax, const arma::mat& X, const arma::vec& Y, const double sigma, const double kappa, const double alpha, const arma::vec& adaptive_weights);
RcppExport SEXP _krtexas_loss_fun_fast_cpp(SEXP uSEXP, SEXP wSEXP, SEXP AxSEXP, SEXP XSEXP, SEXP YSEXP, SEXP sigmaSEXP, SEXP kappaSEXP, SEXP alphaSEXP, SEXP adaptive_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ax(AxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type adaptive_weights(adaptive_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_fun_fast_cpp(u, w, Ax, X, Y, sigma, kappa, alpha, adaptive_weights));
    return rcpp_result_gen;
END_RCPP
}
// get_grad_lqr
arma::mat get_grad_lqr(const arma::mat& X, const arma::vec& y, const arma::mat& X0, const arma::vec& gamma);
RcppExport SEXP _krtexas_get_grad_lqr(SEXP XSEXP, SEXP ySEXP, SEXP X0SEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_grad_lqr(X, y, X0, gamma));
    return rcpp_result_gen;
END_RCPP
}
// get_grad_llr
arma::mat get_grad_llr(const arma::mat& X, const arma::vec& y, const arma::mat& X0, const arma::vec& gamma);
RcppExport SEXP _krtexas_get_grad_llr(SEXP XSEXP, SEXP ySEXP, SEXP X0SEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_grad_llr(X, y, X0, gamma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_krtexas_loss_grad_rcpp", (DL_FUNC) &_krtexas_loss_grad_rcpp, 10},
    {"_krtexas_grad_fun_fast_cpp", (DL_FUNC) &_krtexas_grad_fun_fast_cpp, 8},
    {"_krtexas_interior_scores_exp_kernel_cpp", (DL_FUNC) &_krtexas_interior_scores_exp_kernel_cpp, 4},
    {"_krtexas_find_interior_points", (DL_FUNC) &_krtexas_find_interior_points, 5},
    {"_krtexas_loss_fun_fast_cpp", (DL_FUNC) &_krtexas_loss_fun_fast_cpp, 9},
    {"_krtexas_get_grad_lqr", (DL_FUNC) &_krtexas_get_grad_lqr, 4},
    {"_krtexas_get_grad_llr", (DL_FUNC) &_krtexas_get_grad_llr, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_krtexas(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
