# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loss_grad_rcpp <- function(u, w, Ax, X, Y, sigma, kappa, alpha, adaptive_weights, eps = 1e-12) {
    .Call(`_krtexas_loss_grad_rcpp`, u, w, Ax, X, Y, sigma, kappa, alpha, adaptive_weights, eps)
}

grad_fun_fast_cpp <- function(u, w, Ax, X, Y, sigma, kappa, adaptive_weights) {
    .Call(`_krtexas_grad_fun_fast_cpp`, u, w, Ax, X, Y, sigma, kappa, adaptive_weights)
}

#' Compute interiorness scores using the exp kernel
#'
#' For each sample point X[i,], compute
#'   score[i] = (1/n) * sum_{k=1}^n exp( - sum_{j=1}^p gamma_j * (X[i,j] - X[k,j])^2 )
#' Optionally exclude self-similarity which only shifts all scores by a constant 1.
#'
#' @param X Numeric matrix (n x p): sample points.
#' @param gamma Numeric vector (length p): nonnegative kernel scales per dimension.
#' @param exclude_self logical: if TRUE, set K(X_i, X_i) = 0 in the sum.
#' @param normalize logical: if TRUE, divide by n (number of points).
#' @return Numeric vector (length n): interiorness scores (larger = more interior).
#' @examples
#' \dontrun{
#' scores <- interior_scores_exp_kernel_cpp(X, gamma)
#' order <- order(scores, decreasing = TRUE)
#' }
interior_scores_exp_kernel_cpp <- function(X, gamma, exclude_self = TRUE, normalize = TRUE) {
    .Call(`_krtexas_interior_scores_exp_kernel_cpp`, X, gamma, exclude_self, normalize)
}

#' Find the top-m most interior sample points under the exp kernel
#'
#' @param X Numeric matrix (n x p): sample points.
#' @param gamma Numeric vector (length p): nonnegative kernel scales per dimension.
#' @param m integer: number of most interior points to return.
#' @param exclude_self logical: if TRUE, set K(X_i, X_i) = 0 when scoring.
#' @param normalize logical: if TRUE, divide scores by n.
#' @return A list with elements:
#'   - indices: IntegerVector (length m), 1-based row indices into X (descending by score)
#'   - scores:  NumericVector (length m), the corresponding scores
#'   - X_top:   NumericMatrix (m x p), the top-m points
#'
#' @examples
#' \dontrun{
#' res <- top_interior_points_exp_kernel_cpp(X, gamma, m = 10)
#' res$indices; res$scores; res$X_top
#' }
find_interior_points <- function(X, gamma, m, exclude_self = TRUE, normalize = TRUE) {
    .Call(`_krtexas_find_interior_points`, X, gamma, m, exclude_self, normalize)
}


loss_fun_fast_cpp <- function(u, w, Ax, X, Y, sigma, kappa, alpha, adaptive_weights) {
    .Call(`_krtexas_loss_fun_fast_cpp`, u, w, Ax, X, Y, sigma, kappa, alpha, adaptive_weights)
}

get_grad_lqr <- function(X, y, X0, gamma) {
    .Call(`_krtexas_get_grad_lqr`, X, y, X0, gamma)
}

get_grad_llr <- function(X, y, X0, gamma) {
    .Call(`_krtexas_get_grad_llr`, X, y, X0, gamma)
}

